"""Aggregate all per-experiment ``analysis_summary.json`` files into one report.

Walks ``artifacts/thesis_reproduction/<family>/<model>/analysis_summary.json``,
collects each measured metric (ours mean ± std vs paper mean ± std + z-score
+ verdict), and emits a single comparison table in either Markdown or plain
text. Useful for thesis-defense Q&A and for a one-glance check that the
refactor still reproduces every paper anchor.

Notes:
* ``analysis_summary.json`` is written by ``analyze.py`` at the end of every
  experiment's shell script. If you have older runs that pre-date that
  feature, re-run ``analyze.py --experiment <key>`` to produce the file.
* Experiments routed through specialized analyzers (attention_hijacking,
  trajectory, attention_knockout, downstream_eval, pca_reconstruction) do
  not write analysis_summary.json — they have their own qualitative gates.
  They are listed at the bottom of the report as "specialized analyzer" rows.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def _load_expected(thesis_reproduction_dir: Path) -> dict:
    with open(thesis_reproduction_dir / "expected.json") as f:
        return json.load(f)


def _walk_summaries(artifacts_root: Path) -> dict[str, dict]:
    """Return ``{experiment_key: analysis_summary_dict}`` for everything we find."""
    summaries: dict[str, dict] = {}
    if not artifacts_root.exists():
        return summaries
    for path in sorted(artifacts_root.rglob("analysis_summary.json")):
        rel = path.relative_to(artifacts_root).parent  # <family>/<model>
        try:
            with open(path) as f:
                summaries[str(rel)] = json.load(f)
        except (OSError, json.JSONDecodeError) as e:
            print(f"# warning: could not read {path}: {e}")
    return summaries


def _format_markdown(expected: dict, summaries: dict[str, dict]) -> str:
    """Render the aggregated comparison as a Markdown document."""
    lines: list[str] = [
        "# Verification summary",
        "",
        "Aggregated comparison of every reproduced experiment vs paper anchors.",
        "Generated by `scripts/thesis_reproduction/summarize_verification.py`.",
        "",
        "## Measured metrics (one row per experiment × metric)",
        "",
        "| Experiment | Metric | Ours | Paper | z | Verdict |",
        "|---|---|---:|---:|---:|:---:|",
    ]

    measured_keys = sorted(summaries.keys())
    for key in measured_keys:
        summary = summaries[key]
        for record in summary.get("measured", []):
            ours = f"{record['ours_mean']:.3f} ± {record['ours_std']:.3f}"
            paper = f"{record['paper_mean']:.3f} ± {record['paper_std']:.3f}"
            z = "n/a" if record["z_score"] is None else f"{record['z_score']:.2f}"
            verdict = record["verdict"]
            lines.append(f"| `{key}` | {record['metric']} | {ours} | {paper} | {z} | **{verdict}** |")

    # Experiments that ran but have no analysis_summary.json (specialized analyzers).
    specialized = []
    for key, spec in expected.items():
        if key in summaries:
            continue
        analyzer = spec.get("analyzer")
        if analyzer:
            specialized.append((key, analyzer))

    if specialized:
        lines += [
            "",
            "## Specialized analyzers (qualitative gates, no z-score table)",
            "",
            "| Experiment | Analyzer |",
            "|---|---|",
        ]
        for key, analyzer in sorted(specialized):
            lines.append(f"| `{key}` | `{analyzer}` |")
        lines += [
            "",
            "Run `uv run python scripts/thesis_reproduction/analyze.py --experiment <key>` ",
            "for each of these to see the qualitative verdict.",
        ]

    # Experiments listed in expected.json but never run.
    not_run = [key for key in expected if key not in summaries and not expected[key].get("analyzer")]
    if not_run:
        lines += [
            "",
            "## Not yet run (no analysis_summary.json on disk)",
            "",
        ]
        for key in sorted(not_run):
            lines.append(f"* `{key}` — paper anchor: {expected[key].get('paper_section', '?')}")

    # Final aggregate verdict.
    total = sum(len(s.get("measured", [])) for s in summaries.values())
    ok = sum(1 for s in summaries.values() for r in s.get("measured", []) if r["verdict"] == "OK")
    warn = sum(1 for s in summaries.values() for r in s.get("measured", []) if r["verdict"] == "WARN")
    fail = sum(1 for s in summaries.values() for r in s.get("measured", []) if r["verdict"] == "FAIL")
    lines += [
        "",
        "## Aggregate",
        "",
        f"* Measured metrics across all experiments: **{total}**",
        f"* OK (within 2σ): **{ok}**",
        f"* WARN (within 3σ but outside 2σ): **{warn}**",
        f"* FAIL (beyond 3σ): **{fail}**",
        f"* Specialized-analyzer experiments: **{len(specialized)}**",
        f"* Not yet run: **{len(not_run)}**",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--artifacts_root",
        default="artifacts/thesis_reproduction",
        help="Directory that holds per-experiment subfolders with analysis_summary.json.",
    )
    parser.add_argument(
        "--output",
        default="artifacts/thesis_reproduction/verification_summary.md",
        help="Output Markdown file. Use '-' for stdout.",
    )
    args = parser.parse_args()

    thesis_dir = Path(__file__).parent
    expected = _load_expected(thesis_dir)
    artifacts_root = Path(args.artifacts_root)
    summaries = _walk_summaries(artifacts_root)
    markdown = _format_markdown(expected, summaries)

    if args.output == "-":
        print(markdown)
    else:
        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(markdown)
        print(f"Wrote {out_path} ({len(summaries)} measured-metric experiments)")


if __name__ == "__main__":
    main()
